---
- name: Download and install go binary
  when: (not openstack_exporter__version_check | bool) or (not ansible_check_mode and (openstack_exporter__active_version.stdout != openstack_exporter__version))
  block:
    - name: Download latest release
      ansible.builtin.get_url:
        url: "{{ openstack_exporter__releases }}/{{ openstack_exporter__filename }}.tar.gz"
        dest: "/tmp/{{ openstack_exporter__filename }}.tar.gz"
        # checksum: "sha256:{{ openstack_exporter__releases }}/{{ openstack_exporter__checksum }}"
        mode: 0640
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2

    - name: Run mkdir /opt/openstack-exporter
      become: true
      ansible.builtin.file:
        path: '/opt/openstack-exporter'
        state: 'directory'
        owner: "{{ openstack_exporter__user }}"
        group: "{{ openstack_exporter__group }}"
        mode: '0750'

    - name: Unarchive openstack_exporter
      become: true
      ansible.builtin.unarchive:
        src: "/tmp/{{ openstack_exporter__filename }}.tar.gz"
        dest: '/opt/openstack-exporter'
        owner: "{{ openstack_exporter__user }}"
        group: "{{ openstack_exporter__group }}"
        remote_src: true

    - name: Deploy new openstack_exporter binary
      become: true
      ansible.builtin.copy:
        src: "/opt/openstack-exporter/openstack-exporter"
        remote_src: true
        dest: '/usr/local/bin/openstack-exporter'
        owner: "{{ openstack_exporter__user }}"
        group: "{{ openstack_exporter__group }}"
        mode: '0755'

- name: Install tmux
  become: true
  ansible.builtin.package:
    name: tmux
    state: present
