---
- name: Copy the openstack_exporter systemd service file
  become: true
  ansible.builtin.template:
    src: 'templates/openstack_exporter.service.j2'
    dest: '/etc/systemd/system/openstack_exporter.service'
    owner: root
    group: root
    mode: 0644
  notify: "Systemctl restart openstack_exporter"
