---
- name: Systemctl restart openstack_exporter
  become: true
  ansible.builtin.systemd:
    name: "openstack_exporter.service"
    state: 'restarted'
    daemon_reload: true
  when: openstack_exporter__systemd | bool
